name: hymns
description: A Flutter app for displaying church hymns and their tunes

publish_to: 'none' # This is to avoid publishing to pub.dev

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  provider: ^6.0.0
  flutter_pdfview: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
